
// USER SIGNUP

export const USER_SIGNUP_REQUESTED="USER_SIGNUP_REQUESTED"
export const USER_SIGNUP_SUCCESS="USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL="USER_SIGNUP_FAIL"
export const USER_SIGNUP_ERROR="USER_SIGNUP_ERROR"
export const USER_SIGNUP_LOADING="USER_SIGNUP_LOADING"
export const SET_USER="SET_USER"
export const SET_USER_REQUESTED="SET_USER_REQUESTED"
export const CLEAR_ERROR="CLEAR_ERROR"
export const LOGOUT="LOGOUT"


// USER LOGIN

export const USER_LOGIN_REQUESTED="USER_LOGIN_REQUESTED"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR"
export const USER_LOGIN_LOADING="USER_LOGIN_LOADING"
